export const PLAYER_LOGIN_REQUEST = "PLAYER_LOGIN_REQUEST";
export const PLAYER_LOGIN_SUCCESS = "PLAYER_LOGIN_SUCCESS";
export const PLAYER_LOGIN_FAIL = "PLAYER_LOGIN_FAIL";
export const SET_FIRST_PIN = "SET_FIRST_PIN";
